version: '2'
services:
  servicepfe-app:
    image: servicepfe
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://servicepfe-postgresql:5432/servicePFE
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8041:8041
  servicepfe-postgresql:
    extends:
      file: postgresql.yml
      service: servicepfe-postgresql
